-- MySQL Script generated by MySQL Workbench
-- Τρι 07 Μαΐ 2019 02:08:27 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jobify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobify`;
-- -----------------------------------------------------
-- Schema jobify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobify` DEFAULT CHARACTER SET utf8 ;
USE `jobify` ;

-- -----------------------------------------------------
-- Table `jobify`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hash` VARCHAR(32) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '	',
  `phone` VARCHAR(15) NULL,
  `address` VARCHAR(255) NULL,
  `birthdate` DATE NULL,
  `profession` VARCHAR(50) NULL,
  `native_lang` VARCHAR(30) NULL,
  `description` TEXT NULL,
  `facebook` VARCHAR(100) NULL,
  `linkedin` VARCHAR(100) NULL,
  `cv` VARCHAR(150) NULL,
  `gender` VARCHAR(10) NOT NULL,
  `image` VARCHAR(255) NOT NULL DEFAULT 'assets/img/uploads/users/default_img.png',
  `lat` VARCHAR(50) NOT NULL,
  `long` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `category` VARCHAR(40) NOT NULL,
  `start` YEAR NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `website` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `phone` VARCHAR(15) NULL,
  `facebook` VARCHAR(100) NULL,
  `linkedin` VARCHAR(100) NULL,
  `image` VARCHAR(255) NOT NULL DEFAULT 'assets/img/uploads/companies/default_img.png',
  `lat` VARCHAR(50) NOT NULL,
  `long` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`employers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hash` VARCHAR(32) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `profession` VARCHAR(50) NOT NULL DEFAULT 'Employer',
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_employers_companies1_idx` (`company_id` ASC),
  CONSTRAINT `fk_employers_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `jobify`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`jobs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` VARCHAR(15) NOT NULL,
  `salary` MEDIUMINT UNSIGNED NULL,
  `address` VARCHAR(255) NOT NULL,
  `lat` VARCHAR(50) NOT NULL,
  `long` VARCHAR(50) NOT NULL,
  `views` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_jobs_companies1_idx` (`company_id` ASC),
  CONSTRAINT `fk_jobs_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `jobify`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`applications` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `state` VARCHAR(30) NOT NULL DEFAULT 'Pending',
  INDEX `fk_applications_users1_idx` (`user_id` ASC),
  INDEX `fk_applications_jobs1_idx` (`job_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`job_id`, `user_id`),
  CONSTRAINT `fk_applications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jobify`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_applications_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `jobify`.`jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`skills` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_skills_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_skills_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jobify`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
